backend = "xrender";
vsync = false;

### claude tips for i3 problems fixing
unredir-if-possible = false;
use-damage = false;

# --- Shadows (Disable with shadow = false;)
# The shadow exclude options are helpful if you have shadows enabled.
# Due to the way compton draws its shadows, certain applications (Such as
# shaped windows, custom popups, non-standard toolkits) will have visual glitches.

# Shadow
# tried to dissable to free some cpu
shadow = false;
no-dnd-shadow = true;
no-dock-shadow = true;
shadow-radius = 12.0;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.7;


# --- Fading (Disable with fading = false;)

fading = false;                          # Fade windows during opacity changes.
fade-delta = 3;                         # The time between steps in a fade in milliseconds. (default 5).
fade-in-step = 0.03;            # Opacity change between steps while fading in. (default 0.03).
fade-out-step = 0.04;   # Opacity change between steps while fading out. (default 0.03).


# --- Additional Settings
#detect-client-opacity = true;


# --- Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.75;focus = true; };
};


############################################
# Per‑app opacity
############################################
opacity-rule = [
  "90:class_g = 'qterminal'",
  "90:class_g = 'Code'",
  "90:class_g = 'Sublime_text'",
  "90:class_g = 'obsidian'"
#  "90:class_g = 'Thunar'"
];
